"""Tests for Neural Network Math from Scratch.

DO NOT EDIT THIS FILE. This is the test suite for the capstone project.
Implement your solution in lib/neural_network.py.
"""

import numpy as np
import pytest

from lib.neural_network import (
    Layer,
    MomentumSGD,
    NeuralNetwork,
    SGD,
    Trainer,
    cross_entropy_loss,
    cross_entropy_loss_derivative,
    generate_spiral_data,
    mse_loss,
    mse_loss_derivative,
    one_hot_encode,
    relu,
    relu_derivative,
    sigmoid,
    sigmoid_derivative,
    softmax,
)


# ===========================================================================
# Activation Functions
# ===========================================================================

class TestRelu:
    def test_positive_values_unchanged(self):
        x = np.array([1.0, 2.0, 3.0])
        result = relu(x)
        np.testing.assert_array_equal(result, np.array([1.0, 2.0, 3.0]))

    def test_negative_values_become_zero(self):
        x = np.array([-1.0, -2.0, -3.0])
        result = relu(x)
        np.testing.assert_array_equal(result, np.array([0.0, 0.0, 0.0]))

    def test_mixed_values(self):
        x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
        result = relu(x)
        np.testing.assert_array_equal(result, np.array([0.0, 0.0, 0.0, 1.0, 2.0]))

    def test_preserves_shape(self):
        x = np.array([[1.0, -1.0], [-2.0, 3.0]])
        result = relu(x)
        assert result.shape == (2, 2)


class TestReluDerivative:
    def test_positive_gives_one(self):
        x = np.array([1.0, 2.0, 5.0])
        result = relu_derivative(x)
        np.testing.assert_array_equal(result, np.array([1.0, 1.0, 1.0]))

    def test_negative_gives_zero(self):
        x = np.array([-1.0, -2.0, -5.0])
        result = relu_derivative(x)
        np.testing.assert_array_equal(result, np.array([0.0, 0.0, 0.0]))

    def test_zero_gives_zero(self):
        x = np.array([0.0])
        result = relu_derivative(x)
        np.testing.assert_array_equal(result, np.array([0.0]))


class TestSigmoid:
    def test_zero_gives_half(self):
        result = sigmoid(np.array([0.0]))
        np.testing.assert_almost_equal(result[0], 0.5)

    def test_large_positive_approaches_one(self):
        result = sigmoid(np.array([100.0]))
        assert result[0] > 0.99

    def test_large_negative_approaches_zero(self):
        result = sigmoid(np.array([-100.0]))
        assert result[0] < 0.01

    def test_output_in_zero_one_range(self):
        x = np.random.default_rng(42).standard_normal(100)
        result = sigmoid(x)
        assert np.all(result >= 0.0)
        assert np.all(result <= 1.0)


class TestSigmoidDerivative:
    def test_at_zero(self):
        result = sigmoid_derivative(np.array([0.0]))
        np.testing.assert_almost_equal(result[0], 0.25)

    def test_always_non_negative(self):
        x = np.linspace(-5, 5, 100)
        result = sigmoid_derivative(x)
        assert np.all(result >= 0.0)


class TestSoftmax:
    def test_output_sums_to_one(self):
        x = np.array([1.0, 2.0, 3.0])
        result = softmax(x)
        np.testing.assert_almost_equal(np.sum(result), 1.0)

    def test_invariant_to_constant_shift(self):
        x = np.array([1.0, 2.0, 3.0])
        result1 = softmax(x)
        result2 = softmax(x + 1000.0)
        np.testing.assert_array_almost_equal(result1, result2)

    def test_batch_softmax(self):
        x = np.array([[1.0, 2.0, 3.0], [1.0, 1.0, 1.0]])
        result = softmax(x)
        assert result.shape == (2, 3)
        np.testing.assert_almost_equal(np.sum(result[0]), 1.0)
        np.testing.assert_almost_equal(np.sum(result[1]), 1.0)

    def test_equal_inputs_give_uniform(self):
        x = np.array([1.0, 1.0, 1.0])
        result = softmax(x)
        np.testing.assert_array_almost_equal(result, np.array([1/3, 1/3, 1/3]))


# ===========================================================================
# Loss Functions
# ===========================================================================

class TestMseLoss:
    def test_identical_predictions_give_zero(self):
        preds = np.array([1.0, 2.0, 3.0])
        targets = np.array([1.0, 2.0, 3.0])
        assert mse_loss(preds, targets) == pytest.approx(0.0)

    def test_different_predictions_give_positive(self):
        preds = np.array([1.0, 2.0])
        targets = np.array([2.0, 3.0])
        assert mse_loss(preds, targets) == pytest.approx(1.0)

    def test_known_value(self):
        preds = np.array([0.0, 0.0])
        targets = np.array([1.0, 1.0])
        assert mse_loss(preds, targets) == pytest.approx(1.0)


class TestMseLossDerivative:
    def test_shape_matches_input(self):
        preds = np.array([1.0, 2.0, 3.0])
        targets = np.array([1.0, 2.0, 3.0])
        result = mse_loss_derivative(preds, targets)
        assert result.shape == preds.shape

    def test_zero_gradient_for_perfect_prediction(self):
        preds = np.array([1.0, 2.0])
        targets = np.array([1.0, 2.0])
        result = mse_loss_derivative(preds, targets)
        np.testing.assert_array_almost_equal(result, np.zeros(2))


class TestCrossEntropyLoss:
    def test_perfect_prediction_near_zero(self):
        preds = np.array([[0.99, 0.005, 0.005]])
        targets = np.array([[1.0, 0.0, 0.0]])
        loss = cross_entropy_loss(preds, targets)
        assert loss < 0.02

    def test_bad_prediction_high_loss(self):
        preds = np.array([[0.01, 0.01, 0.98]])
        targets = np.array([[1.0, 0.0, 0.0]])
        loss = cross_entropy_loss(preds, targets)
        assert loss > 2.0

    def test_loss_is_non_negative(self):
        preds = np.array([[0.3, 0.3, 0.4]])
        targets = np.array([[0.0, 0.0, 1.0]])
        loss = cross_entropy_loss(preds, targets)
        assert loss >= 0.0


class TestCrossEntropyLossDerivative:
    def test_shape_matches_input(self):
        preds = np.array([[0.7, 0.2, 0.1]])
        targets = np.array([[1.0, 0.0, 0.0]])
        result = cross_entropy_loss_derivative(preds, targets)
        assert result.shape == preds.shape


# ===========================================================================
# Layer
# ===========================================================================

class TestLayer:
    def test_weights_shape(self):
        layer = Layer(10, 5)
        assert layer.weights.shape == (10, 5)

    def test_biases_shape(self):
        layer = Layer(10, 5)
        assert layer.biases.shape == (1, 5)

    def test_he_initialization_std(self):
        layer = Layer(1000, 500, seed=42)
        expected_std = np.sqrt(2.0 / 1000)
        actual_std = np.std(layer.weights)
        assert abs(actual_std - expected_std) < 0.05

    def test_forward_output_shape(self):
        layer = Layer(10, 5)
        x = np.random.default_rng(0).standard_normal((32, 10))
        output = layer.forward(x)
        assert output.shape == (32, 5)

    def test_forward_with_sigmoid(self):
        layer = Layer(4, 3, activation="sigmoid", seed=0)
        x = np.random.default_rng(1).standard_normal((8, 4))
        output = layer.forward(x)
        assert output.shape == (8, 3)
        assert np.all(output >= 0.0)
        assert np.all(output <= 1.0)

    def test_backward_returns_correct_shape(self):
        layer = Layer(10, 5)
        x = np.random.default_rng(0).standard_normal((4, 10))
        layer.forward(x)
        grad_output = np.random.default_rng(1).standard_normal((4, 5))
        grad_input = layer.backward(grad_output)
        assert grad_input.shape == (4, 10)

    def test_backward_stores_gradients(self):
        layer = Layer(10, 5)
        x = np.random.default_rng(0).standard_normal((4, 10))
        layer.forward(x)
        grad_output = np.random.default_rng(1).standard_normal((4, 5))
        layer.backward(grad_output)
        assert layer.grad_weights.shape == (10, 5)
        assert layer.grad_biases.shape == (1, 5)


# ===========================================================================
# Neural Network
# ===========================================================================

class TestNeuralNetwork:
    def test_forward_output_shape(self):
        net = NeuralNetwork([10, 8, 3])
        x = np.random.default_rng(0).standard_normal((16, 10))
        output = net.forward(x)
        assert output.shape == (16, 3)

    def test_predict_returns_integers(self):
        net = NeuralNetwork([10, 5, 3])
        x = np.random.default_rng(0).standard_normal((8, 10))
        preds = net.predict(x)
        assert preds.shape == (8,)
        assert np.issubdtype(preds.dtype, np.integer)

    def test_layer_count(self):
        net = NeuralNetwork([10, 8, 6, 3])
        assert len(net.layers) == 3

    def test_three_layer_forward_valid_output(self):
        net = NeuralNetwork([20, 16, 8, 4])
        x = np.random.default_rng(0).standard_normal((5, 20))
        output = net.forward(x)
        assert output.shape == (5, 4)
        # Softmax output should sum to ~1 for each sample
        row_sums = np.sum(output, axis=1)
        np.testing.assert_array_almost_equal(row_sums, np.ones(5))

    def test_default_activations(self):
        net = NeuralNetwork([10, 8, 6, 3])
        assert net.layers[0].activation == "relu"
        assert net.layers[1].activation == "relu"
        assert net.layers[2].activation == "softmax"


# ===========================================================================
# Optimizers
# ===========================================================================

class TestSGD:
    def test_weights_change_after_update(self):
        layer = Layer(4, 3, seed=0)
        x = np.random.default_rng(1).standard_normal((2, 4))
        layer.forward(x)
        layer.backward(np.ones((2, 3)))
        weights_before = layer.weights.copy()
        optimizer = SGD(learning_rate=0.1)
        optimizer.update([layer])
        assert not np.array_equal(layer.weights, weights_before)

    def test_learning_rate_affects_step_size(self):
        layer1 = Layer(4, 3, seed=0)
        layer2 = Layer(4, 3, seed=0)
        x = np.random.default_rng(1).standard_normal((2, 4))
        layer1.forward(x)
        layer1.backward(np.ones((2, 3)))
        layer2.forward(x)
        layer2.backward(np.ones((2, 3)))
        w_before = layer1.weights.copy()
        SGD(learning_rate=0.1).update([layer1])
        SGD(learning_rate=0.01).update([layer2])
        diff1 = np.abs(layer1.weights - w_before).sum()
        diff2 = np.abs(layer2.weights - w_before).sum()
        assert diff1 > diff2


class TestMomentumSGD:
    def test_weights_change_after_update(self):
        layer = Layer(4, 3, seed=0)
        x = np.random.default_rng(1).standard_normal((2, 4))
        layer.forward(x)
        layer.backward(np.ones((2, 3)))
        weights_before = layer.weights.copy()
        optimizer = MomentumSGD(learning_rate=0.1, momentum=0.9)
        optimizer.update([layer])
        assert not np.array_equal(layer.weights, weights_before)

    def test_momentum_builds_velocity(self):
        """After multiple steps with same gradient, momentum should make larger updates."""
        layer = Layer(4, 3, seed=0)
        optimizer = MomentumSGD(learning_rate=0.01, momentum=0.9)
        x = np.random.default_rng(1).standard_normal((2, 4))

        # First step
        layer.forward(x)
        layer.backward(np.ones((2, 3)))
        w_before_1 = layer.weights.copy()
        optimizer.update([layer])
        step1 = np.abs(layer.weights - w_before_1).sum()

        # Second step with same gradient direction
        layer.forward(x)
        layer.backward(np.ones((2, 3)))
        w_before_2 = layer.weights.copy()
        optimizer.update([layer])
        step2 = np.abs(layer.weights - w_before_2).sum()

        assert step2 > step1  # Momentum should increase step size


# ===========================================================================
# Trainer
# ===========================================================================

class TestTrainer:
    def _make_trainer(self, lr=0.1):
        net = NeuralNetwork([2, 16, 3], seed=42)
        opt = SGD(learning_rate=lr)
        return Trainer(net, opt, cross_entropy_loss, cross_entropy_loss_derivative)

    def test_train_step_returns_loss(self):
        trainer = self._make_trainer()
        x = np.random.default_rng(0).standard_normal((8, 2))
        y = one_hot_encode(np.array([0, 1, 2, 0, 1, 2, 0, 1]), 3)
        loss = trainer.train_step(x, y)
        assert isinstance(loss, float)
        assert loss > 0.0

    def test_train_returns_loss_history(self):
        trainer = self._make_trainer()
        x = np.random.default_rng(0).standard_normal((30, 2))
        y = one_hot_encode(np.repeat([0, 1, 2], 10), 3)
        result = trainer.train(x, y, epochs=5, batch_size=10)
        assert "loss_history" in result
        assert len(result["loss_history"]) == 5

    def test_loss_decreases_over_training(self):
        x, labels = generate_spiral_data(n_points_per_class=50, n_classes=3, seed=42)
        y = one_hot_encode(labels, 3)
        net = NeuralNetwork([2, 32, 16, 3], seed=42)
        opt = SGD(learning_rate=0.1)
        trainer = Trainer(net, opt, cross_entropy_loss, cross_entropy_loss_derivative)
        result = trainer.train(x, y, epochs=30, batch_size=32, seed=42)
        assert result["loss_history"][-1] < result["loss_history"][0]

    def test_evaluate_returns_accuracy_and_loss(self):
        trainer = self._make_trainer()
        x = np.random.default_rng(0).standard_normal((10, 2))
        y = one_hot_encode(np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0]), 3)
        result = trainer.evaluate(x, y)
        assert "accuracy" in result
        assert "loss" in result
        assert 0.0 <= result["accuracy"] <= 1.0

    def test_batch_processing(self):
        """Training with different batch sizes should work."""
        trainer = self._make_trainer()
        x = np.random.default_rng(0).standard_normal((20, 2))
        y = one_hot_encode(np.tile([0, 1, 2, 0], 5), 3)
        # Small batches
        result = trainer.train(x, y, epochs=3, batch_size=5)
        assert len(result["loss_history"]) == 3


# ===========================================================================
# Helper Functions
# ===========================================================================

class TestOneHotEncode:
    def test_shape(self):
        labels = np.array([0, 1, 2])
        result = one_hot_encode(labels, 3)
        assert result.shape == (3, 3)

    def test_values_are_zero_or_one(self):
        labels = np.array([0, 1, 2, 0, 1])
        result = one_hot_encode(labels, 3)
        assert set(np.unique(result)) == {0.0, 1.0}

    def test_correct_encoding(self):
        labels = np.array([0, 1, 2])
        result = one_hot_encode(labels, 3)
        expected = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]], dtype=float)
        np.testing.assert_array_equal(result, expected)


class TestGenerateSpiralData:
    def test_output_shape(self):
        x, y = generate_spiral_data(n_points_per_class=50, n_classes=3)
        assert x.shape == (150, 2)
        assert y.shape == (150,)

    def test_deterministic_with_seed(self):
        x1, y1 = generate_spiral_data(seed=123)
        x2, y2 = generate_spiral_data(seed=123)
        np.testing.assert_array_equal(x1, x2)
        np.testing.assert_array_equal(y1, y2)

    def test_correct_class_counts(self):
        _, y = generate_spiral_data(n_points_per_class=100, n_classes=3)
        for c in range(3):
            assert np.sum(y == c) == 100


# ===========================================================================
# Integration Tests
# ===========================================================================

class TestIntegration:
    def test_xor_like_classification(self):
        """Network should learn a nonlinear 2D classification pattern."""
        rng = np.random.default_rng(42)
        # Create XOR-like data
        x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]] * 25, dtype=float)
        labels = np.array([0, 1, 1, 0] * 25)
        x += rng.normal(0, 0.1, x.shape)  # Add noise
        y = one_hot_encode(labels, 2)

        net = NeuralNetwork([2, 16, 2], activations=["relu", "softmax"], seed=42)
        opt = SGD(learning_rate=0.5)
        trainer = Trainer(net, opt, cross_entropy_loss, cross_entropy_loss_derivative)
        result = trainer.train(x, y, epochs=100, batch_size=20, seed=42)
        assert result["loss_history"][-1] < result["loss_history"][0]

    def test_loss_decreases_during_training(self):
        x, labels = generate_spiral_data(n_points_per_class=100, n_classes=3, seed=0)
        y = one_hot_encode(labels, 3)
        net = NeuralNetwork([2, 64, 32, 3], seed=0)
        opt = SGD(learning_rate=0.1)
        trainer = Trainer(net, opt, cross_entropy_loss, cross_entropy_loss_derivative)
        result = trainer.train(x, y, epochs=50, batch_size=32, seed=0)
        # Loss should decrease significantly
        assert result["loss_history"][-1] < result["loss_history"][0] * 0.5

    def test_spiral_classification_above_chance(self):
        """Trained network should beat random chance on spiral data."""
        x, labels = generate_spiral_data(n_points_per_class=100, n_classes=3, seed=7)
        y = one_hot_encode(labels, 3)
        net = NeuralNetwork([2, 64, 32, 3], seed=7)
        opt = SGD(learning_rate=0.1)
        trainer = Trainer(net, opt, cross_entropy_loss, cross_entropy_loss_derivative)
        trainer.train(x, y, epochs=100, batch_size=32, seed=7)
        result = trainer.evaluate(x, y)
        assert result["accuracy"] > 0.4  # Chance is ~0.33

    def test_momentum_converges_faster(self):
        """MomentumSGD should converge faster than vanilla SGD."""
        x, labels = generate_spiral_data(n_points_per_class=80, n_classes=3, seed=42)
        y = one_hot_encode(labels, 3)

        # Vanilla SGD
        net1 = NeuralNetwork([2, 32, 3], seed=42)
        opt1 = SGD(learning_rate=0.05)
        trainer1 = Trainer(net1, opt1, cross_entropy_loss, cross_entropy_loss_derivative)
        result1 = trainer1.train(x, y, epochs=30, batch_size=32, seed=42)

        # Momentum SGD
        net2 = NeuralNetwork([2, 32, 3], seed=42)
        opt2 = MomentumSGD(learning_rate=0.05, momentum=0.9)
        trainer2 = Trainer(net2, opt2, cross_entropy_loss, cross_entropy_loss_derivative)
        result2 = trainer2.train(x, y, epochs=30, batch_size=32, seed=42)

        # Momentum should achieve lower loss
        assert result2["loss_history"][-1] < result1["loss_history"][-1]
